// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijbdhoigjfunsxaoqoow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYmRob2lnamZ1bnN4YW9xb293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjM0NzYsImV4cCI6MjA2NzUzOTQ3Nn0.0ugWZyDVCYlYzU1jASsV8Va2ZQ6w_C4B2gHMgvxn25s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});